# backend/api/events_v2.py
from typing import List, Dict, Any
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from dotenv import load_dotenv
import os, hashlib, json, uuid
from datetime import datetime, timezone

from backend.db import SessionLocal
from backend.repositories import sql_repo as repo
from backend.api.ai import SYS_ANNOT_PROMPT, USER_BATCH_PROMPT

load_dotenv()
router = APIRouter()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def _uuid(prefix: str) -> str:
    return f"{prefix}.{uuid.uuid4().hex[:12]}"


def _clean_json_response(content: str) -> str:
    content = content.strip()
    if content.startswith("```json"): content = content[7:]
    if content.endswith("```"): content = content[:-3]
    return content.strip()


@router.post("/propose_missing/{transcript_id}")
def propose_missing(transcript_id: str, db: Session = Depends(get_db)):
    # 1. 获取数据
    segs = repo.list_unlabeled_segments(db, transcript_id, limit=100)
    if not segs:
        return {"created": 0, "message": "No unlabeled segments found."}

    # 2. 准备 Codebook 缓存 (Name -> ID)
    cb_rows = repo.list_codebook(db, include_deprecated=False)
    codebook_map = {c['name']: c['id'] for c in cb_rows}

    # 准备 Prompt 上下文
    cb_simple = [{"name": c["name"], "definition": c.get("definition", "")} for c in cb_rows]
    cb_json = json.dumps(cb_simple, ensure_ascii=False)

    recent_events = repo.get_recent_accepted_events(db, transcript_id, limit=5)
    context_lines = []
    if recent_events:
        for r in recent_events:
            code = r.get('code_name') or "Uncategorized"
            context_lines.append(f"- Example: '{r['summary']}' -> Code: <{code}>")
    context_str = "\n".join(context_lines) or "(No approved events yet.)"

    use_openai = os.getenv("OPENAI_API_KEY") and os.getenv("USE_EMBEDDINGS", "1") not in ("0", "false", "")
    created_count = 0

    def process_batch(batch_segs):
        nonlocal created_count
        try:
            from openai import OpenAI
            base_url = os.getenv("OPENAI_BASE_URL") or os.getenv("OPENAI_API_BASE_URL")
            client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"), base_url=base_url) if base_url else OpenAI()
            model = os.getenv("OPENAI_LLM_MODEL", "gpt-4o-mini")

            segments_payload = json.dumps([{
                "id": s["id"],
                "text": s["text"][:300]
            } for s in batch_segs], ensure_ascii=False)

            final_user_msg = USER_BATCH_PROMPT.format(
                context_str=context_str,
                n_codes=len(cb_simple),  # ✨ 新增：告诉 Prompt 我们有多少个 Code
                codebook_json=cb_json,
                segments_json=segments_payload
            )

            resp = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": SYS_ANNOT_PROMPT},
                    {"role": "user", "content": final_user_msg}
                ],
                temperature=0.1
            )

            content = _clean_json_response(resp.choices[0].message.content or "{}")
            data = json.loads(content)
            results = data.get("results", [])

            now_str = datetime.now(timezone.utc).isoformat()

            for item in results:
                seg_id = item.get("id")
                summary = item.get("summary")
                code_name = (item.get("code_name") or "").strip()

                original_seg = next((s for s in batch_segs if s["id"] == seg_id), None)
                if not original_seg or not summary: continue

                eid = f"e.{seg_id}"

                # 1. 创建 Event
                repo.create_event(db, {
                    "id": eid,
                    "transcript_id": transcript_id,
                    "segment_id": seg_id,
                    "summary": summary,
                    "created_by": "AI",
                    "status": "proposed",
                    "confidence": 0.8,
                    "created_at": now_str,
                    "raw_excerpt": original_seg["text"][:200]
                })

                # 2. 处理 Code (关键修复：支持自动创建)
                if code_name and code_name.lower() != "null":
                    # A. 检查缓存
                    cb_id = codebook_map.get(code_name)

                    # B. 如果缓存里没有，创建新的
                    if not cb_id:
                        new_id = _uuid("cb")
                        repo.create_codebook_item(db, {
                            "id": new_id,
                            "name": code_name,
                            "definition": f"Auto-generated by AI during batch processing",
                            "status": "proposed",  # 标记为待审核
                            "created_at": now_str
                        })
                        # 更新缓存，防止同批次重复创建
                        codebook_map[code_name] = new_id
                        cb_id = new_id

                    # C. 添加 Label
                    repo.add_event_label(db, eid, cb_id, "AI", None)

                created_count += 1

            db.commit()

        except Exception as e:
            print(f"Batch error: {e}")
            db.rollback()

    if use_openai:
        BATCH_SIZE = 30
        for i in range(0, len(segs), BATCH_SIZE):
            batch = segs[i: i + BATCH_SIZE]
            process_batch(batch)

    return {"created": created_count}


@router.get("/with_labels/{transcript_id}")
def get_events_with_labels(transcript_id: str, db: Session = Depends(get_db)):
    return repo.get_events_with_labels_sorted(db, transcript_id)